# File: docker-compose.yaml
# Assignment: MS Capstone
# Lanuguage: YAML
# Author: Sean Kells <spk3077@rit.edu>
# Description: Runs IText environment and exploit
version: "3.8"

services:
  # Maven Build JARs
  build_jars:
    image: maven:3.8.5-openjdk-17
    volumes:
      - ./springboot:/app
    working_dir: /app
    command: mvn clean package

  # Springboot
  springboot:
    image: eclipse-temurin:17-jdk-alpine
    volumes:
      - ./springboot/target/IText-1.0.0.jar:/app.jar
      - ./pdfs:/pdfs
      - ../../payloads/images/injected:/images
    working_dir: /
    entrypoint: ["java","-jar","/app.jar"]
    depends_on:
      build_jars:
        condition: service_completed_successfully
    ports:
      - 80:80