# File: docker-compose.yaml
# Assignment: MS Capstone
# Lanuguage: YAML
# Author: Sean Kells <spk3077@rit.edu>
# Description: Runs PikePDF environment and exploit
version: "3"

services:
  webserver:
    build: .
    volumes:
      - ./pikepdf_test:/usr/src/app
      - ../../payloads/images/injected:/images/
      - ./pdfs:/pdfs/
      - ../../payloads/py_payloads.py:/usr/src/app/py_payloads.py
      - ../../payloads/views.py:/usr/src/app/base/views.py
    ports:
      - 80:80